CREATE TABLE empresa_config (
  emp_id int(11) NOT NULL AUTO_INCREMENT,
  ID_CPF_EMPRESA varchar(100) COLLATE latin1_general_ci DEFAULT NULL,  
  emp_razaosocial varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_nomefantasia varchar(100) COLLATE latin1_general_ci DEFAULT NULL,  
  emp_ie varchar(100) COLLATE latin1_general_ci DEFAULT NULL,    
  emp_iest varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_insc_mun varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_cnae varchar(100) COLLATE latin1_general_ci DEFAULT NULL,  
  emp_crt varchar(100) COLLATE latin1_general_ci DEFAULT NULL,  
  emp_cnpj varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_cpf varchar(100) COLLATE latin1_general_ci DEFAULT NULL,    
  emp_endereco varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_numero varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_complemento varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_bairro varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_cod_municipio varchar(100) COLLATE latin1_general_ci DEFAULT NULL,   
  emp_nome_municipio varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_sigla_uf char(2) COLLATE latin1_general_ci DEFAULT NULL,
  emp_codigo_estado char(2) COLLATE latin1_general_ci DEFAULT NULL,
  emp_cep varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_nome_pais varchar(100) COLLATE latin1_general_ci DEFAULT NULL,  
  emp_cod_pais varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_contato1 varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_contato2 varchar(100) COLLATE latin1_general_ci DEFAULT NULL,  
  emp_email varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_facebook varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  emp_siteurl varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  PRIMARY KEY (emp_id)
) 